# 换行宽度，当代码宽度达到多少时换行
printWidth: 100
# 缩进的空格数量
tabWidth: 4
# 是否使用制表符代替空格
useTabs: false
# 是否在代码块结尾加上分号
semi: true
# 是否使用单引号替代双引号
singleQuote: true
# 指定对象字面量中的属性名引号添加方式。 可选项：
# as-needed - 只在需要的情况下加引号。
# consistent - 有一个需要引号就给其他都统一加上。
# preserve - 保留用户输入的引号。
quoteProps: 'as-needed'
# jsx中是否使用单引号替代双引号
jsxSingleQuote: true
# 指定添加尾后逗号的方式。 选项：
# none - 无尾后逗号。
# es5 - 在 ES5 中有效的尾后逗号（如对象与数组等）。
# all - 尽可能添加尾后逗号（如函数的参数列表）。
trailingComma: 'none'
# 在对象，数组括号与文字之间加空格 "{ foo: bar }"
bracketSpacing: true
# 把多行HTML (HTML, JSX, Vue, Angular)元素的>放在最后一行的末尾，而不是单独放在下一行(不适用于自关闭元素)。
bracketSameLine: false
# 箭头函数只有一个参数是否加括号{"always"|"avoid"}
arrowParens: 'always'
# 指定 HTML 文件的空白字符敏感度。 可选项：
# css - 以 CSS 的 display 属性为准。
# strict - 空白字符敏感。
# ignore - 空白字符不敏感。
htmlWhitespaceSensitivity: 'ignore'
# 是否缩进Vue文件中的<script>和<style>标记内的代码。有些人(比如Vue的创建者)不使用缩进来保存缩进级别，但这可能会破坏编辑器中的代码折叠。
vueIndentScriptAndStyle: false
# 指定 Prettier 使用的换行符
endOfLine: 'crlf'
# 因为使用了一些折行敏感型的渲染器（如GitHub comment）而按照markdown文本样式进行折行
proseWrap: 'never'
# 是否使用根目录下的EditorConfig配置文件
useEditorConfig: false
# HTML\VUE\JSX属性单独占一行
singleAttributePerLine: true
# 禁用语言
disableLanguages: ['html']
